// Code generated by the klever-sc build system. DO NOT EDIT.
////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           14
// Total number of exported functions:  16

#![no_std]

klever_sc_wasm_adapter::allocator!();
klever_sc_wasm_adapter::panic_handler!();

klever_sc_wasm_adapter::endpoints! {
    bridge_proxy
    (
        init => init
        upgrade => upgrade
        deposit => deposit
        execute => execute
        getPendingTransactionById => get_pending_transaction_by_id
        getPendingTransactions => get_pending_transactions
        setMultiTransferAddress => set_multi_transfer_contract_address
        setBridgedTokensWrapperAddress => set_bridged_tokens_wrapper_contract_address
        setKdaSafeAddress => set_kda_safe_contract_address
        getMultiTransferAddress => multi_transfer_address
        getBridgedTokensWrapperAddress => bridged_tokens_wrapper_address
        getKdaSafeContractAddress => kda_safe_contract_address
        highestTxId => highest_tx_id
        pause => pause_endpoint
        unpause => unpause_endpoint
        isPaused => paused_status
    )
}
