[settings]
main = "bridged-tokens-wrapper"

# the only purpose of this config is to specify the allocator
[contracts.bridged-tokens-wrapper]
allocator = "static64k"

[[proxy]]
path = "../multi-transfer-kda/src/bridged_tokens_wrapper_proxy.rs"

[[proxy]]
path = "../multisig/src/bridged_tokens_wrapper_proxy.rs"

[[proxy]]
path = "../bridge-proxy/src/bridged_tokens_wrapper_proxy.rs"