// Code generated by the klever-sc build system. DO NOT EDIT.
////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           22
// Total number of exported functions:  24

#![no_std]

klever_sc_wasm_adapter::allocator!(static64k);
klever_sc_wasm_adapter::panic_handler!();

klever_sc_wasm_adapter::endpoints! {
    multi_transfer_kda
    (
        init => init
        upgrade => upgrade
        batchTransferKdaToken => batch_transfer_kda_token
        moveRefundBatchToSafe => move_refund_batch_to_safe
        setWrappingContractAddress => set_wrapping_contract_address
        addUnprocessedRefundTxToBatch => add_unprocessed_refund_tx_to_batch
        setKdaSafeContractAddress => set_kda_safe_contract_address
        changeContractName => change_contract_name
        getWrappingContractAddress => wrapping_contract_address
        getKdaSafeContractAddress => kda_safe_contract_address
        setMaxTxBatchSize => set_max_tx_batch_size
        setMaxTxBatchBlockDuration => set_max_tx_batch_block_duration
        getCurrentTxBatch => get_current_tx_batch
        getFirstBatchAnyStatus => get_first_batch_any_status
        getBatch => get_batch
        getBatchStatus => get_batch_status
        getFirstBatchId => first_batch_id
        getLastBatchId => last_batch_id
        setMaxBridgedAmount => set_max_bridged_amount
        getMaxBridgedAmount => max_bridged_amount
        isAdmin => is_admin
        addAdmin => add_admin
        removeAdmin => remove_admin
        getAdmins => admins
    )
}
