// Code generated by the klever-sc build system. DO NOT EDIT.
////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           17
// Total number of exported functions:  19

#![no_std]

klever_sc_wasm_adapter::allocator!(static64k);
klever_sc_wasm_adapter::panic_handler!();

klever_sc_wasm_adapter::endpoints! {
    bridged_tokens_wrapper
    (
        init => init
        upgrade => upgrade
        addWrappedToken => add_wrapped_token
        updateWrappedToken => update_wrapped_token
        removeWrappedToken => remove_wrapped_token
        whitelistToken => whitelist_token
        updateWhitelistedToken => update_whitelisted_token
        blacklistToken => blacklist_token
        depositLiquidity => deposit_liquidity
        wrapTokens => wrap_tokens
        unwrapToken => unwrap_token
        unwrapTokenCreateTransaction => unwrap_token_create_transaction
        getUniversalBridgedTokenIds => universal_bridged_token_ids
        getTokenLiquidity => token_liquidity
        getChainSpecificToUniversalMapping => chain_specific_to_universal_mapping
        getchainSpecificTokenIds => chain_specific_token_ids
        pause => pause_endpoint
        unpause => unpause_endpoint
        isPaused => paused_status
    )
}
